# Generated by Django 5.1.2 on 2024-11-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_social", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="content_html",
            field=models.TextField(),
        ),
    ]
