# Generated by Django 5.1.2 on 2024-11-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_social", "0002_alter_page_content_html"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="privacy",
            field=models.CharField(
                choices=[
                    ("public", "Công khai"),
                    ("friends", "Bạn bè"),
                    ("private", "Chỉ mình tôi"),
                    ("blocked", "Blocked"),
                ],
                default="public",
                max_length=10,
            ),
        ),
    ]
