# Generated by Django 5.1.2 on 2024-11-11 06:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web_social", "0004_userprofile_deletion_requested_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="share",
            old_name="created_at",
            new_name="shared_at",
        ),
    ]
