# Generated by Django 5.1.2 on 2024-11-13 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_social", "0006_post_posted_on_wall"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="web_social.page",
            ),
        ),
    ]
