# Generated by Django 5.1.2 on 2024-11-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_social", "0008_friendrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
