# Generated by Django 5.1.2 on 2024-11-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_social", "0012_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
