# Generated by Django 5.1.2 on 2024-11-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_social", "0014_page_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_recalled",
            field=models.BooleanField(default=False),
        ),
    ]
